## Question 1

### Setting:

Let's have an input space X being the temperature of a room in degreese Celsius.

Let our output space Y be the energy consumed by an air conditioner per hour, in kilowatt-hours.

Our joint random variable (X, Y) follows a joint distribution where:
- The temperature X ~ u(20, 30) (uniform distribution between 20 and 30 degrees).
- The output Y = 0.5 * (X - 20) + e, with e ~ N(0, 0.01)

So, Y | X = x ~ N(0.5(x - 20), 0.01).

For our loss functions, we choose the squarred loss:
- l(y, ŷ) = (y - ŷ)^2

### Bayes predictor f*(x):

With the squarred loss, the Bayes predictor is the conditional mean:

- f*(x) = E[Y | X = x] = 0.5(x - 20)

### Bayes Risk R(f*):

The Bayes risk is the expected loss using the Bayes predictor:

- R(f*) = E[(Y - f*(X))^2] = E[Var(Y | X)]

Since Y | X = x ~ N(f*(x), 0.01), the conditional variance is constant:

- R(f*) = 0.01

## Question 2

In [ ]:
import numpy as np

rng = np.random.default_rng(seed=8080)

n_samples = int(1e6)
X = rng.uniform(20, 30, n_samples).astype(float)
y = 0.5 * (X - 20) + rng.normal(0, 0.1)

y_pred_bayes = 0.5 * (X - 20)

# Our own predictor will just predict random values between 0 and 5 which is the domain of Y
y_pred_bad = rng.uniform(0, 5, n_samples).astype(float)

empirical_risk_bayes = np.mean(np.square(y - y_pred_bayes))

empirical_risk_bad_estimator = np.mean(np.square(y - y_pred_bad))

print("\nX:")
print(X)
print("\ny:")
print(y)
print("\ny pred bad:")
print(y_pred_bad.astype(int))
print("\ny pred Bayes:")
print(y_pred_bayes.astype(int))
print("\nEmpirical risk for Bayes predictor squared loss:")
print(empirical_risk_bayes)
print("\nEmpirical risk for bad predictor squared loss:")
print(empirical_risk_bad_estimator)


X:
[22.12789982 25.80353569 26.35337412 ... 27.7886574  21.2350486
 23.21175806]

y:
[1.16863644 3.00645437 3.28137359 ... 3.99901523 0.72221083 1.71056556]

y pred bad:
[1 3 1 ... 4 1 0]

y pred Bayes:
[1 2 3 ... 3 0 1]

Empirical risk for Bayes predictor squared loss:
0.010959269725041793

Empirical risk for bad predictor squared loss:
4.184853790728646


We can see from our random example that our empirical risk for our Bayes predictor is close to the one we computed in question 1.

Also, we can see that our empirical risk for our own predictor is way worse than the Bayes' one.